# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_server.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServerScreen(object):
    def setupUi(self, ServerScreen):
        ServerScreen.setObjectName("ServerScreen")
        ServerScreen.resize(700, 360)
        self.centralwidget = QtWidgets.QWidget(ServerScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_border = QtWidgets.QFrame(self.centralwidget)
        self.frame_border.setGeometry(QtCore.QRect(0, 0, 700, 360))
        self.frame_border.setStyleSheet("QFrame {    \n"
"    background-color: rgba(18, 18, 18, 175);    \n"
"}\n"
"QLabel {\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_border.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_border.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_border.setObjectName("frame_border")
        self.frame = QtWidgets.QFrame(self.frame_border)
        self.frame.setGeometry(QtCore.QRect(10, 10, 680, 340))
        self.frame.setStyleSheet("QFrame {    \n"
"    background-color: rgba(18, 18, 18, 225);    \n"
"}\n"
"QLabel {\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 680, 340))
        self.widget.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 680, 70))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(42)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(20, 92, 158);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 680, 30))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(224,224,226);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btn_chat = QtWidgets.QPushButton(self.widget)
        self.btn_chat.setGeometry(QtCore.QRect(20, 150, 120, 120))
        self.btn_chat.setStyleSheet("QPushButton#btn_chat {\n"
"    border-image: url(:/images/images/chat.png);\n"
"}\n"
"QPushButton#btn_chat:hover {\n"
"    border-image: url(:/images/images/hover_chat.png);\n"
"}")
        self.btn_chat.setText("")
        self.btn_chat.setObjectName("btn_chat")
        self.btn_download = QtWidgets.QPushButton(self.widget)
        self.btn_download.setGeometry(QtCore.QRect(150, 150, 120, 120))
        self.btn_download.setStyleSheet("QPushButton#btn_download {\n"
"    border-image: url(:/images/images/download.png);\n"
"}\n"
"QPushButton#btn_download:hover {\n"
"    border-image: url(:/images/images/hover_download.png);\n"
"}")
        self.btn_download.setText("")
        self.btn_download.setObjectName("btn_download")
        self.btn_restart = QtWidgets.QPushButton(self.widget)
        self.btn_restart.setGeometry(QtCore.QRect(410, 150, 120, 120))
        self.btn_restart.setStyleSheet("QPushButton#btn_restart {\n"
"    border-image: url(:/images/images/restart.png);\n"
"}\n"
"QPushButton#btn_restart:hover {\n"
"    border-image: url(:/images/images/hover_restart.png);\n"
"}")
        self.btn_restart.setText("")
        self.btn_restart.setObjectName("btn_restart")
        self.btn_shutdown = QtWidgets.QPushButton(self.widget)
        self.btn_shutdown.setGeometry(QtCore.QRect(540, 150, 120, 120))
        self.btn_shutdown.setStyleSheet("QPushButton#btn_shutdown {\n"
"    border-image: url(:/images/images/shutdown.png);\n"
"}\n"
"QPushButton#btn_shutdown:hover {\n"
"    border-image: url(:/images/images/hover_shutdown.png);\n"
"}")
        self.btn_shutdown.setText("")
        self.btn_shutdown.setObjectName("btn_shutdown")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(224,224,226);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(150, 120, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(224,224,226);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(280, 120, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(224,224,226);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(410, 120, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(224,224,226);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_chat = QtWidgets.QLabel(self.widget)
        self.label_chat.setGeometry(QtCore.QRect(20, 270, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.label_chat.setFont(font)
        self.label_chat.setStyleSheet("color: rgb(224,224,226);")
        self.label_chat.setAlignment(QtCore.Qt.AlignCenter)
        self.label_chat.setObjectName("label_chat")
        self.label_download = QtWidgets.QLabel(self.widget)
        self.label_download.setGeometry(QtCore.QRect(150, 270, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.label_download.setFont(font)
        self.label_download.setStyleSheet("color: rgb(224,224,226);")
        self.label_download.setAlignment(QtCore.Qt.AlignCenter)
        self.label_download.setObjectName("label_download")
        self.btn_logs = QtWidgets.QPushButton(self.widget)
        self.btn_logs.setGeometry(QtCore.QRect(280, 150, 120, 120))
        self.btn_logs.setStyleSheet("QPushButton#btn_logs {\n"
"    border-image: url(:/images/images/logs.png);\n"
"}\n"
"QPushButton#btn_logs:hover {\n"
"    border-image: url(:/images/images/hover_logs.png);\n"
"}")
        self.btn_logs.setText("")
        self.btn_logs.setObjectName("btn_logs")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(540, 120, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(224,224,226);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        ServerScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(ServerScreen)
        QtCore.QMetaObject.connectSlotsByName(ServerScreen)

    def retranslateUi(self, ServerScreen):
        _translate = QtCore.QCoreApplication.translate
        ServerScreen.setWindowTitle(_translate("ServerScreen", "MainWindow"))
        self.label.setText(_translate("ServerScreen", "Прело"))
        self.label_2.setText(_translate("ServerScreen", "Подешавања сервера"))
        self.label_3.setText(_translate("ServerScreen", "Дописивање"))
        self.label_4.setText(_translate("ServerScreen", "Скидање музике"))
        self.label_5.setText(_translate("ServerScreen", "Лог фајл"))
        self.label_6.setText(_translate("ServerScreen", "Рестарт"))
        self.label_chat.setText(_translate("ServerScreen", "УКЉУЧЕНО"))
        self.label_download.setText(_translate("ServerScreen", "УКЉУЧЕНО"))
        self.label_7.setText(_translate("ServerScreen", "Угаси"))
import res_rc
