# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_upload.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UploadScreen(object):
    def setupUi(self, UploadScreen):
        UploadScreen.setObjectName("UploadScreen")
        UploadScreen.resize(700, 360)
        self.centralwidget = QtWidgets.QWidget(UploadScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_border = QtWidgets.QFrame(self.centralwidget)
        self.frame_border.setGeometry(QtCore.QRect(0, 0, 700, 360))
        self.frame_border.setStyleSheet("QFrame {    \n"
"    background-color: rgba(18, 18, 18, 175);    \n"
"}\n"
"QLabel {\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_border.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_border.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_border.setObjectName("frame_border")
        self.frame = QtWidgets.QFrame(self.frame_border)
        self.frame.setGeometry(QtCore.QRect(10, 10, 680, 340))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 680, 340))
        self.widget.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"}")
        self.widget.setObjectName("widget")
        self.app = QtWidgets.QLabel(self.widget)
        self.app.setGeometry(QtCore.QRect(0, 0, 680, 70))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(42)
        font.setBold(True)
        font.setWeight(75)
        self.app.setFont(font)
        self.app.setStyleSheet("color: rgb(20, 92, 158);")
        self.app.setAlignment(QtCore.Qt.AlignCenter)
        self.app.setObjectName("app")
        self.app_2 = QtWidgets.QLabel(self.widget)
        self.app_2.setGeometry(QtCore.QRect(0, 60, 680, 30))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        self.app_2.setFont(font)
        self.app_2.setStyleSheet("color: rgb(224,224,226);")
        self.app_2.setAlignment(QtCore.Qt.AlignCenter)
        self.app_2.setObjectName("app_2")
        self.btn_back = QtWidgets.QPushButton(self.widget)
        self.btn_back.setGeometry(QtCore.QRect(620, 20, 41, 41))
        self.btn_back.setStyleSheet("QPushButton#btn_back {\n"
"    border-image: url(:/images/images/back.png);\n"
"}\n"
"QPushButton#btn_back:hover {\n"
"    border-image: url(:/images/images/hover_back.png);\n"
"}")
        self.btn_back.setText("")
        self.btn_back.setObjectName("btn_back")
        self.btn_open = QtWidgets.QPushButton(self.widget)
        self.btn_open.setGeometry(QtCore.QRect(20, 20, 41, 41))
        self.btn_open.setStyleSheet("QPushButton#btn_open {\n"
"    border-image: url(:/images/images/open.png);\n"
"}\n"
"QPushButton#btn_open:hover {\n"
"    border-image: url(:/images/images/hover_open.png);\n"
"}")
        self.btn_open.setText("")
        self.btn_open.setObjectName("btn_open")
        self.list_files = QtWidgets.QListWidget(self.widget)
        self.list_files.setGeometry(QtCore.QRect(20, 100, 641, 221))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.list_files.setFont(font)
        self.list_files.setStyleSheet("QListWidget#list_files {\n"
"    color: rgb(224,224,226);\n"
"    background-color:rgba(0,0,0,0);\n"
"    border: 2px solid rgb(20,92,158);\n"
"    border-radius: 5px;\n"
"}\n"
"QListWidget::item:hover {\n"
"    background-color: rgb(20,92,158);\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(19,55,88);\n"
"}")
        self.list_files.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_files.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_files.setObjectName("list_files")
        self.btn_upload = QtWidgets.QPushButton(self.widget)
        self.btn_upload.setGeometry(QtCore.QRect(120, 20, 41, 41))
        self.btn_upload.setStyleSheet("QPushButton#btn_upload {\n"
"    border-image: url(:/images/images/upload.png);\n"
"}\n"
"QPushButton#btn_upload:hover {\n"
"    border-image: url(:/images/images/hover_upload.png);\n"
"}")
        self.btn_upload.setText("")
        self.btn_upload.setObjectName("btn_upload")
        self.btn_delete = QtWidgets.QPushButton(self.widget)
        self.btn_delete.setGeometry(QtCore.QRect(70, 20, 41, 41))
        self.btn_delete.setStyleSheet("QPushButton#btn_delete {\n"
"    border-image: url(:/images/images/delete.png);\n"
"}\n"
"QPushButton#btn_delete:hover {\n"
"    border-image: url(:/images/images/hover_delete.png);\n"
"}")
        self.btn_delete.setText("")
        self.btn_delete.setObjectName("btn_delete")
        UploadScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(UploadScreen)
        QtCore.QMetaObject.connectSlotsByName(UploadScreen)

    def retranslateUi(self, UploadScreen):
        _translate = QtCore.QCoreApplication.translate
        UploadScreen.setWindowTitle(_translate("UploadScreen", "MainWindow"))
        self.app.setText(_translate("UploadScreen", "Прело"))
        self.app_2.setText(_translate("UploadScreen", "Додавање нове музике"))
import res_rc
