# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatScreen(object):
    def setupUi(self, ChatScreen):
        ChatScreen.setObjectName("ChatScreen")
        ChatScreen.setWindowModality(QtCore.Qt.NonModal)
        ChatScreen.resize(490, 600)
        ChatScreen.setWindowOpacity(1.0)
        ChatScreen.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(ChatScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_border = QtWidgets.QFrame(self.centralwidget)
        self.frame_border.setGeometry(QtCore.QRect(0, 0, 490, 600))
        self.frame_border.setStyleSheet("QFrame {    \n"
"    background-color: rgba(18, 18, 18, 175);\n"
"}\n"
"QLabel {\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_border.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_border.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_border.setObjectName("frame_border")
        self.frame = QtWidgets.QFrame(self.frame_border)
        self.frame.setGeometry(QtCore.QRect(10, 10, 470, 580))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 470, 580))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.app_name = QtWidgets.QLabel(self.widget)
        self.app_name.setGeometry(QtCore.QRect(130, 0, 190, 60))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(42)
        font.setBold(True)
        font.setWeight(75)
        self.app_name.setFont(font)
        self.app_name.setStyleSheet("color: rgb(20, 92, 158);")
        self.app_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.app_name.setAlignment(QtCore.Qt.AlignCenter)
        self.app_name.setObjectName("app_name")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(194, 35, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(224,224,226);")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.btn_back = QtWidgets.QPushButton(self.widget)
        self.btn_back.setGeometry(QtCore.QRect(430, 10, 30, 30))
        self.btn_back.setStyleSheet("QPushButton#btn_back {\n"
"    border-image: url(:/menu/images/menu/exit.png);\n"
"}\n"
"QPushButton#btn_back:hover {\n"
"    border-image: url(:/menu/images/menu/hover_exit.png);\n"
"}")
        self.btn_back.setText("")
        self.btn_back.setObjectName("btn_back")
        self.frame_left = QtWidgets.QFrame(self.widget)
        self.frame_left.setGeometry(QtCore.QRect(0, 0, 130, 580))
        self.frame_left.setStyleSheet("QPushButton {\n"
"    background-color: rgb(20, 92, 158);\n"
"    color: rgb(224, 224, 226);\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(19, 55, 88);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(19, 37, 53);\n"
"}")
        self.frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.btn_global = QtWidgets.QPushButton(self.frame_left)
        self.btn_global.setGeometry(QtCore.QRect(0, 40, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_global.setFont(font)
        self.btn_global.setStyleSheet("")
        self.btn_global.setObjectName("btn_global")
        self.options = QtWidgets.QLabel(self.frame_left)
        self.options.setGeometry(QtCore.QRect(0, 0, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.options.setFont(font)
        self.options.setStyleSheet("color: rgb(224, 224, 226);")
        self.options.setAlignment(QtCore.Qt.AlignCenter)
        self.options.setObjectName("options")
        self.friends = QtWidgets.QLabel(self.frame_left)
        self.friends.setGeometry(QtCore.QRect(0, 80, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.friends.setFont(font)
        self.friends.setStyleSheet("color: rgb(224, 224, 226);")
        self.friends.setAlignment(QtCore.Qt.AlignCenter)
        self.friends.setObjectName("friends")
        self.list_friends = QtWidgets.QListWidget(self.frame_left)
        self.list_friends.setGeometry(QtCore.QRect(0, 120, 130, 451))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(8)
        self.list_friends.setFont(font)
        self.list_friends.setStyleSheet("QListWidget#list_friends {\n"
"    color: rgb(224,224,226);\n"
"    background-color:rgba(0,0,0,0);\n"
"    border-radius: 0px;\n"
"}\n"
"QListWidget::item:hover {\n"
"    background-color: rgb(20,92,158);\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(19,55,88);\n"
"}")
        self.list_friends.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_friends.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_friends.setObjectName("list_friends")
        self.stacked_pages = QtWidgets.QStackedWidget(self.widget)
        self.stacked_pages.setGeometry(QtCore.QRect(130, 70, 340, 510))
        self.stacked_pages.setStyleSheet("QPlainTextEdit#chat_global, #chat_friend {\n"
"    color: rgb(224,224,226);\n"
"    background-color:rgba(0,0,0,0);\n"
"    border: 2px solid rgb(20,92,158);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgba(0,0,0,0);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(20, 92, 158);\n"
"    color: rgb(224, 224, 226);\n"
"    padding-left: 5px;\n"
"}\n"
"QPushButton#btn_send, #btn_send_2, #btn_refresh {\n"
"    background-color: rgb(20, 92, 158);\n"
"    color: rgb(224, 224, 226);\n"
"    border-radius: 5px;\n"
"}\n"
"QListWidget#list_global, #list_friend {\n"
"    color: rgb(224,224,226);\n"
"    background-color:rgba(0,0,0,0);\n"
"    border: 2px solid rgb(20,92,158);\n"
"    border-radius: 5px;\n"
"}\n"
"QListWidget::item:hover {\n"
"    background-color: rgb(20,92,158);\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(19,55,88);\n"
"}")
        self.stacked_pages.setObjectName("stacked_pages")
        self.page_global = QtWidgets.QWidget()
        self.page_global.setStyleSheet("")
        self.page_global.setObjectName("page_global")
        self.btn_send = QtWidgets.QPushButton(self.page_global)
        self.btn_send.setGeometry(QtCore.QRect(240, 460, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_send.setFont(font)
        self.btn_send.setStyleSheet("QPushButton#btn_send {\n"
"    border-image: url(:/icons/images/icons/send.png);\n"
"}\n"
"QPushButton#btn_send:hover {\n"
"    border-image: url(:/icons/images/icons/hover_send.png);\n"
"}")
        self.btn_send.setText("")
        self.btn_send.setObjectName("btn_send")
        self.input_msg = QtWidgets.QLineEdit(self.page_global)
        self.input_msg.setGeometry(QtCore.QRect(10, 460, 220, 40))
        self.input_msg.setClearButtonEnabled(True)
        self.input_msg.setObjectName("input_msg")
        self.chat_global = QtWidgets.QPlainTextEdit(self.page_global)
        self.chat_global.setGeometry(QtCore.QRect(10, 10, 320, 440))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(8)
        self.chat_global.setFont(font)
        self.chat_global.setStyleSheet("")
        self.chat_global.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chat_global.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chat_global.setReadOnly(True)
        self.chat_global.setPlainText("")
        self.chat_global.setObjectName("chat_global")
        self.btn_refresh = QtWidgets.QPushButton(self.page_global)
        self.btn_refresh.setGeometry(QtCore.QRect(290, 460, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_refresh.setFont(font)
        self.btn_refresh.setStyleSheet("QPushButton#btn_refresh {\n"
"    border-image: url(:/icons/images/icons/refresh.png);\n"
"}\n"
"QPushButton#btn_refresh:hover {\n"
"    border-image: url(:/icons/images/icons/hover_refresh.png);\n"
"}")
        self.btn_refresh.setText("")
        self.btn_refresh.setObjectName("btn_refresh")
        self.stacked_pages.addWidget(self.page_global)
        self.page_friend = QtWidgets.QWidget()
        self.page_friend.setStyleSheet("QLabel#label_art {\n"
"    border: 2px solid;\n"
"    background-color: rgb(224,224,226);\n"
"}")
        self.page_friend.setObjectName("page_friend")
        self.btn_send_2 = QtWidgets.QPushButton(self.page_friend)
        self.btn_send_2.setGeometry(QtCore.QRect(290, 460, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_send_2.setFont(font)
        self.btn_send_2.setStyleSheet("QPushButton#btn_send_2 {\n"
"    border-image: url(:/icons/images/icons/send.png);\n"
"}\n"
"QPushButton#btn_send_2:hover {\n"
"    border-image: url(:/icons/images/icons/hover_send.png);\n"
"}")
        self.btn_send_2.setText("")
        self.btn_send_2.setObjectName("btn_send_2")
        self.label_art = QtWidgets.QLabel(self.page_friend)
        self.label_art.setGeometry(QtCore.QRect(10, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.label_art.setFont(font)
        self.label_art.setStyleSheet("")
        self.label_art.setAlignment(QtCore.Qt.AlignCenter)
        self.label_art.setObjectName("label_art")
        self.label_name = QtWidgets.QLabel(self.page_friend)
        self.label_name.setGeometry(QtCore.QRect(80, 10, 171, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("color: rgb(224, 224, 226);")
        self.label_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_name.setObjectName("label_name")
        self.label_user = QtWidgets.QLabel(self.page_friend)
        self.label_user.setGeometry(QtCore.QRect(80, 30, 171, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_user.setFont(font)
        self.label_user.setStyleSheet("color: rgb(224, 224, 226);")
        self.label_user.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user.setObjectName("label_user")
        self.input_msg_2 = QtWidgets.QLineEdit(self.page_friend)
        self.input_msg_2.setGeometry(QtCore.QRect(10, 460, 270, 40))
        self.input_msg_2.setClearButtonEnabled(True)
        self.input_msg_2.setObjectName("input_msg_2")
        self.chat_friend = QtWidgets.QPlainTextEdit(self.page_friend)
        self.chat_friend.setGeometry(QtCore.QRect(10, 80, 320, 370))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(8)
        self.chat_friend.setFont(font)
        self.chat_friend.setStyleSheet("")
        self.chat_friend.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chat_friend.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chat_friend.setReadOnly(True)
        self.chat_friend.setPlainText("")
        self.chat_friend.setObjectName("chat_friend")
        self.stacked_pages.addWidget(self.page_friend)
        self.app_bg = QtWidgets.QLabel(self.frame_border)
        self.app_bg.setGeometry(QtCore.QRect(0, 0, 490, 600))
        self.app_bg.setStyleSheet("border-image: url(:/images/images/welcome_bg.png);")
        self.app_bg.setText("")
        self.app_bg.setObjectName("app_bg")
        self.app_bg.raise_()
        self.frame.raise_()
        ChatScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChatScreen)
        self.stacked_pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ChatScreen)

    def retranslateUi(self, ChatScreen):
        _translate = QtCore.QCoreApplication.translate
        ChatScreen.setWindowTitle(_translate("ChatScreen", "MainWindow"))
        self.app_name.setText(_translate("ChatScreen", "Прело"))
        self.label.setText(_translate("ChatScreen", "СНАГА КРАЈИНЕ"))
        self.btn_global.setText(_translate("ChatScreen", "Јавно дописивање"))
        self.options.setText(_translate("ChatScreen", "Опције"))
        self.friends.setText(_translate("ChatScreen", "Пријатељи"))
        self.input_msg.setPlaceholderText(_translate("ChatScreen", "Унесите поруку..."))
        self.chat_global.setPlaceholderText(_translate("ChatScreen", "Учитавање порука..."))
        self.label_art.setText(_translate("ChatScreen", "ART"))
        self.label_name.setText(_translate("ChatScreen", "Артис"))
        self.label_user.setText(_translate("ChatScreen", "Пјесмица"))
        self.input_msg_2.setPlaceholderText(_translate("ChatScreen", "Унесите поруку..."))
        self.chat_friend.setPlaceholderText(_translate("ChatScreen", "Учитавање порука..."))
import res_rc
