# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutScreen(object):
    def setupUi(self, AboutScreen):
        AboutScreen.setObjectName("AboutScreen")
        AboutScreen.setWindowModality(QtCore.Qt.NonModal)
        AboutScreen.resize(490, 600)
        AboutScreen.setWindowOpacity(1.0)
        AboutScreen.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(AboutScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_border = QtWidgets.QFrame(self.centralwidget)
        self.frame_border.setGeometry(QtCore.QRect(0, 0, 490, 601))
        self.frame_border.setStyleSheet("QFrame {    \n"
"    background-color: rgba(18, 18, 18, 175);\n"
"}\n"
"QLabel {\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_border.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_border.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_border.setObjectName("frame_border")
        self.frame = QtWidgets.QFrame(self.frame_border)
        self.frame.setGeometry(QtCore.QRect(10, 10, 470, 580))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 471, 580))
        self.widget.setStyleSheet("QPushButton#btn_fb, #btn_ig, #btn_yt, #btn_in, #btn_git {\n"
"    background-color: rgba(0,0,0,0);\n"
"    color: rgb(20,92,158);\n"
"}\n"
"QPushButton#btn_fb:hover, #btn_ig:hover, #btn_yt:hover, #btn_in:hover, #btn_git:hover {\n"
"    color: rgb(19,55,88);\n"
"    font-size: 64px\n"
"}\n"
"QPushButton#btn_fb:pressed, #btn_ig:pressed, #btn_yt:pressed, #btn_in:pressed, #btn_git:pressed {\n"
"    color: rgb(19,37,53);\n"
"}\n"
"QPlainTextEdit {\n"
"    background-color: rgba(0,0,0,0);\n"
"    color: rgb(224,224,226);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(20,92,158);\n"
"    padding-top: 4px;\n"
"}")
        self.widget.setObjectName("widget")
        self.app_name = QtWidgets.QLabel(self.widget)
        self.app_name.setGeometry(QtCore.QRect(0, 0, 191, 60))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(42)
        font.setBold(True)
        font.setWeight(75)
        self.app_name.setFont(font)
        self.app_name.setStyleSheet("color: rgb(20, 92, 158);")
        self.app_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.app_name.setAlignment(QtCore.Qt.AlignCenter)
        self.app_name.setObjectName("app_name")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(70, 35, 111, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(224,224,226);")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.btn_back = QtWidgets.QPushButton(self.widget)
        self.btn_back.setGeometry(QtCore.QRect(430, 10, 30, 30))
        self.btn_back.setStyleSheet("QPushButton#btn_back {\n"
"    border-image: url(:/menu/images/menu/exit.png);\n"
"}\n"
"QPushButton#btn_back:hover {\n"
"    border-image: url(:/menu/images/menu/hover_exit.png);\n"
"}")
        self.btn_back.setText("")
        self.btn_back.setObjectName("btn_back")
        self.btn_in = QtWidgets.QPushButton(self.widget)
        self.btn_in.setGeometry(QtCore.QRect(2, 430, 70, 70))
        self.btn_in.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(40)
        self.btn_in.setFont(font)
        self.btn_in.setObjectName("btn_in")
        self.btn_git = QtWidgets.QPushButton(self.widget)
        self.btn_git.setGeometry(QtCore.QRect(2, 500, 70, 70))
        self.btn_git.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.btn_git.setFont(font)
        self.btn_git.setObjectName("btn_git")
        self.text_yt = QtWidgets.QPlainTextEdit(self.widget)
        self.text_yt.setGeometry(QtCore.QRect(30, 368, 430, 54))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_yt.setFont(font)
        self.text_yt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.text_yt.setStyleSheet("border-left: none;")
        self.text_yt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_yt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_yt.setReadOnly(True)
        self.text_yt.setObjectName("text_yt")
        self.btn_yt = QtWidgets.QPushButton(self.widget)
        self.btn_yt.setGeometry(QtCore.QRect(2, 360, 70, 70))
        self.btn_yt.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(40)
        self.btn_yt.setFont(font)
        self.btn_yt.setObjectName("btn_yt")
        self.btn_follow = QtWidgets.QPushButton(self.widget)
        self.btn_follow.setGeometry(QtCore.QRect(10, 95, 450, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_follow.setFont(font)
        self.btn_follow.setStyleSheet("QPushButton#btn_follow {\n"
"    background-color: rgb(20,92,158);\n"
"    color: rgb(224,224,226);\n"
"    border-radius: 5px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"QPushButton#btn_follow:hover {\n"
"    background-color: rgb(19,55,88);\n"
"}\n"
"QPushButton#btn_follow:pressed {\n"
"    background-color: rgb(19,37,53);\n"
"}")
        self.btn_follow.setObjectName("btn_follow")
        self.text_app = QtWidgets.QPlainTextEdit(self.widget)
        self.text_app.setGeometry(QtCore.QRect(10, 130, 450, 70))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_app.setFont(font)
        self.text_app.setStyleSheet("")
        self.text_app.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_app.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_app.setReadOnly(True)
        self.text_app.setObjectName("text_app")
        self.text_git = QtWidgets.QPlainTextEdit(self.widget)
        self.text_git.setGeometry(QtCore.QRect(30, 508, 430, 54))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.text_git.setFont(font)
        self.text_git.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.text_git.setStyleSheet("border-left: none;")
        self.text_git.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_git.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_git.setReadOnly(True)
        self.text_git.setObjectName("text_git")
        self.text_ig = QtWidgets.QPlainTextEdit(self.widget)
        self.text_ig.setGeometry(QtCore.QRect(30, 298, 430, 54))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_ig.setFont(font)
        self.text_ig.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.text_ig.setStyleSheet("border-left: none;")
        self.text_ig.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_ig.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_ig.setReadOnly(True)
        self.text_ig.setObjectName("text_ig")
        self.btn_fb = QtWidgets.QPushButton(self.widget)
        self.btn_fb.setGeometry(QtCore.QRect(2, 220, 70, 70))
        self.btn_fb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(40)
        self.btn_fb.setFont(font)
        self.btn_fb.setStyleSheet("")
        self.btn_fb.setObjectName("btn_fb")
        self.text_fb = QtWidgets.QPlainTextEdit(self.widget)
        self.text_fb.setGeometry(QtCore.QRect(30, 228, 430, 54))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.text_fb.setFont(font)
        self.text_fb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.text_fb.setStyleSheet("border-left: none;")
        self.text_fb.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_fb.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_fb.setReadOnly(True)
        self.text_fb.setObjectName("text_fb")
        self.text_in = QtWidgets.QPlainTextEdit(self.widget)
        self.text_in.setGeometry(QtCore.QRect(30, 438, 430, 54))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.text_in.setFont(font)
        self.text_in.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.text_in.setStyleSheet("border-left: none;")
        self.text_in.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_in.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_in.setReadOnly(True)
        self.text_in.setObjectName("text_in")
        self.btn_ig = QtWidgets.QPushButton(self.widget)
        self.btn_ig.setGeometry(QtCore.QRect(2, 290, 70, 70))
        self.btn_ig.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(40)
        self.btn_ig.setFont(font)
        self.btn_ig.setObjectName("btn_ig")
        self.app_name.raise_()
        self.label.raise_()
        self.btn_back.raise_()
        self.text_yt.raise_()
        self.text_app.raise_()
        self.text_git.raise_()
        self.text_ig.raise_()
        self.text_fb.raise_()
        self.text_in.raise_()
        self.btn_follow.raise_()
        self.btn_git.raise_()
        self.btn_fb.raise_()
        self.btn_ig.raise_()
        self.btn_yt.raise_()
        self.btn_in.raise_()
        self.app_bg = QtWidgets.QLabel(self.frame_border)
        self.app_bg.setGeometry(QtCore.QRect(0, 0, 491, 601))
        self.app_bg.setStyleSheet("border-image: url(:/images/images/welcome_bg.png);")
        self.app_bg.setText("")
        self.app_bg.setObjectName("app_bg")
        self.app_bg.raise_()
        self.frame.raise_()
        AboutScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(AboutScreen)
        QtCore.QMetaObject.connectSlotsByName(AboutScreen)

    def retranslateUi(self, AboutScreen):
        _translate = QtCore.QCoreApplication.translate
        AboutScreen.setWindowTitle(_translate("AboutScreen", "MainWindow"))
        self.app_name.setText(_translate("AboutScreen", "Прело"))
        self.label.setText(_translate("AboutScreen", "СНАГА КРАЈИНЕ"))
        self.btn_in.setText(_translate("AboutScreen", "C"))
        self.btn_git.setText(_translate("AboutScreen", ")"))
        self.text_yt.setPlainText(_translate("AboutScreen", "      Сабскрајб на наш јутјуб канал.\n"
"      www.youtube.com"))
        self.btn_yt.setText(_translate("AboutScreen", "M"))
        self.btn_follow.setText(_translate("AboutScreen", "ПРАТИТЕ НАС"))
        self.text_app.setPlainText(_translate("AboutScreen", "Прело је апликација намјењена љубитељима народне музике."))
        self.text_git.setPlainText(_translate("AboutScreen", "      Пратите пројекат и на гитхабу.\n"
"      github.com/nikola-supic/"))
        self.text_ig.setPlainText(_translate("AboutScreen", "      Запратите нас на инстаграму.\n"
"      www.instagram.com/dzast_nikola/"))
        self.btn_fb.setText(_translate("AboutScreen", "E"))
        self.text_fb.setPlainText(_translate("AboutScreen", "      Потражите нас на фејсбуку.\n"
"      www.facebook.com/nikola.supic01/"))
        self.text_in.setPlainText(_translate("AboutScreen", "      Пронађите нас и овде.\n"
"      www.linkedin.com/in/nikola-šupić/"))
        self.btn_ig.setText(_translate("AboutScreen", "Q"))
import res_rc
