# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_party.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PartyScreen(object):
    def setupUi(self, PartyScreen):
        PartyScreen.setObjectName("PartyScreen")
        PartyScreen.setWindowModality(QtCore.Qt.NonModal)
        PartyScreen.resize(490, 600)
        PartyScreen.setWindowOpacity(1.0)
        PartyScreen.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(PartyScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_border = QtWidgets.QFrame(self.centralwidget)
        self.frame_border.setGeometry(QtCore.QRect(0, 0, 490, 601))
        self.frame_border.setStyleSheet("QFrame {    \n"
"    background-color: rgba(18, 18, 18, 175);\n"
"}\n"
"QLabel {\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_border.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_border.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_border.setObjectName("frame_border")
        self.frame = QtWidgets.QFrame(self.frame_border)
        self.frame.setGeometry(QtCore.QRect(10, 10, 470, 580))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 471, 580))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.app_name = QtWidgets.QLabel(self.widget)
        self.app_name.setGeometry(QtCore.QRect(10, 0, 191, 60))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(42)
        font.setBold(True)
        font.setWeight(75)
        self.app_name.setFont(font)
        self.app_name.setStyleSheet("color: rgb(20, 92, 158);")
        self.app_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.app_name.setAlignment(QtCore.Qt.AlignCenter)
        self.app_name.setObjectName("app_name")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(75, 35, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(224,224,226);")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.btn_back = QtWidgets.QPushButton(self.widget)
        self.btn_back.setGeometry(QtCore.QRect(420, 20, 30, 30))
        self.btn_back.setStyleSheet("QPushButton#btn_back {\n"
"    border-image: url(:/menu/images/menu/exit.png);\n"
"}\n"
"QPushButton#btn_back:hover {\n"
"    border-image: url(:/menu/images/menu/hover_exit.png);\n"
"}")
        self.btn_back.setText("")
        self.btn_back.setObjectName("btn_back")
        self.frame_bottom = QtWidgets.QFrame(self.widget)
        self.frame_bottom.setGeometry(QtCore.QRect(0, 490, 470, 90))
        self.frame_bottom.setStyleSheet("")
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.label_art = QtWidgets.QLabel(self.frame_bottom)
        self.label_art.setGeometry(QtCore.QRect(20, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.label_art.setFont(font)
        self.label_art.setStyleSheet("border-image: url(:/art/images/art/art_1.png);")
        self.label_art.setText("")
        self.label_art.setAlignment(QtCore.Qt.AlignCenter)
        self.label_art.setObjectName("label_art")
        self.label_artist = QtWidgets.QLabel(self.frame_bottom)
        self.label_artist.setGeometry(QtCore.QRect(100, 20, 230, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_artist.setFont(font)
        self.label_artist.setStyleSheet("color: rgb(224, 224, 226);")
        self.label_artist.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_artist.setObjectName("label_artist")
        self.label_name = QtWidgets.QLabel(self.frame_bottom)
        self.label_name.setGeometry(QtCore.QRect(100, 0, 230, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("color: rgb(224, 224, 226);")
        self.label_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_name.setObjectName("label_name")
        self.btn_queue = QtWidgets.QPushButton(self.frame_bottom)
        self.btn_queue.setGeometry(QtCore.QRect(420, 50, 30, 30))
        self.btn_queue.setStyleSheet("QPushButton#btn_queue {\n"
"    border-image: url(:/party/images/party/queue.png);\n"
"}\n"
"QPushButton#btn_queue:hover {\n"
"    border-image: url(:/party/images/party/hover_queue.png);\n"
"}")
        self.btn_queue.setText("")
        self.btn_queue.setObjectName("btn_queue")
        self.btn_chat = QtWidgets.QPushButton(self.frame_bottom)
        self.btn_chat.setGeometry(QtCore.QRect(420, 10, 30, 30))
        self.btn_chat.setStyleSheet("QPushButton#btn_chat {\n"
"    border-image: url(:/menu/images/menu/chat.png);\n"
"}\n"
"QPushButton#btn_chat:hover {\n"
"    border-image: url(:/menu/images/menu/hover_chat.png);\n"
"}")
        self.btn_chat.setText("")
        self.btn_chat.setObjectName("btn_chat")
        self.btn_dislike = QtWidgets.QPushButton(self.frame_bottom)
        self.btn_dislike.setGeometry(QtCore.QRect(380, 50, 30, 30))
        self.btn_dislike.setStyleSheet("QPushButton#btn_dislike {\n"
"    border-image: url(:/party/images/party/dislike.png);\n"
"}\n"
"QPushButton#btn_dislike:hover {\n"
"    border-image: url(:/party/images/party/hover_dislike.png);\n"
"}")
        self.btn_dislike.setText("")
        self.btn_dislike.setObjectName("btn_dislike")
        self.btn_like = QtWidgets.QPushButton(self.frame_bottom)
        self.btn_like.setGeometry(QtCore.QRect(380, 10, 30, 30))
        self.btn_like.setStyleSheet("QPushButton#btn_like {\n"
"    border-image: url(:/party/images/party/like.png);\n"
"}\n"
"QPushButton#btn_like:hover {\n"
"    border-image: url(:/party/images/party/hover_like.png);\n"
"}")
        self.btn_like.setText("")
        self.btn_like.setObjectName("btn_like")
        self.label_like = QtWidgets.QLabel(self.frame_bottom)
        self.label_like.setGeometry(QtCore.QRect(345, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_like.setFont(font)
        self.label_like.setStyleSheet("color: rgb(224, 224, 226);")
        self.label_like.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_like.setObjectName("label_like")
        self.label_dislike = QtWidgets.QLabel(self.frame_bottom)
        self.label_dislike.setGeometry(QtCore.QRect(345, 50, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_dislike.setFont(font)
        self.label_dislike.setStyleSheet("color: rgb(224, 224, 226);")
        self.label_dislike.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_dislike.setObjectName("label_dislike")
        self.song_status = QtWidgets.QSlider(self.frame_bottom)
        self.song_status.setGeometry(QtCore.QRect(100, 70, 230, 16))
        self.song_status.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: rgb(224,224,226);\n"
"    height: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    width: 12px;\n"
"    background-color: rgb(20,92,158);\n"
"    border-radius: 5px;\n"
"    margin: -5px 0;\n"
"}")
        self.song_status.setSingleStep(1)
        self.song_status.setPageStep(0)
        self.song_status.setProperty("value", 13)
        self.song_status.setSliderPosition(13)
        self.song_status.setTracking(True)
        self.song_status.setOrientation(QtCore.Qt.Horizontal)
        self.song_status.setTickInterval(0)
        self.song_status.setObjectName("song_status")
        self.label_time = QtWidgets.QLabel(self.frame_bottom)
        self.label_time.setGeometry(QtCore.QRect(100, 40, 60, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("color: rgb(224, 224, 226);")
        self.label_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time.setObjectName("label_time")
        self.label_length = QtWidgets.QLabel(self.frame_bottom)
        self.label_length.setGeometry(QtCore.QRect(270, 40, 61, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_length.setFont(font)
        self.label_length.setStyleSheet("color: rgb(224, 224, 226);")
        self.label_length.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_length.setObjectName("label_length")
        self.label_art.raise_()
        self.label_artist.raise_()
        self.label_name.raise_()
        self.btn_queue.raise_()
        self.btn_chat.raise_()
        self.label_like.raise_()
        self.label_dislike.raise_()
        self.btn_dislike.raise_()
        self.btn_like.raise_()
        self.song_status.raise_()
        self.label_time.raise_()
        self.label_length.raise_()
        self.stacked_pages = QtWidgets.QStackedWidget(self.widget)
        self.stacked_pages.setGeometry(QtCore.QRect(0, 70, 470, 420))
        self.stacked_pages.setStyleSheet("QStackedWidget#stacked_pages {\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"")
        self.stacked_pages.setObjectName("stacked_pages")
        self.page_party = QtWidgets.QWidget()
        self.page_party.setStyleSheet("QPushButton#btn_head, #btn_arms, #btn_add, #btn_download {\n"
"    background-color: rgb(20, 92, 158);\n"
"    color: rgb(224, 224, 226);\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    background-color: rgb(18, 18, 18);\n"
"    height: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    width: 12px;\n"
"    background-color: rgb(19,55,88);\n"
"    border-radius: 5px;\n"
"    margin: -5px 0;\n"
"}\n"
"\n"
"\n"
"QSlider::groove:vertical {\n"
"    background-color: rgb(18, 18, 18);\n"
"    width: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    height: 12px;\n"
"    background-color: rgb(19,55,88);\n"
"    border-radius: 5px;\n"
"    margin: 0px -5px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QLabel#label_bg, #label_bg_2, #label_bg_3 {\n"
"    background-color: rgb(20, 92, 158);\n"
"    color: rgb(224, 224, 226);\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}")
        self.page_party.setObjectName("page_party")
        self.btn_head = QtWidgets.QPushButton(self.page_party)
        self.btn_head.setGeometry(QtCore.QRect(420, 10, 30, 30))
        self.btn_head.setStyleSheet("QPushButton#btn_head {\n"
"    border-image: url(:/party/images/party/head.png);\n"
"}\n"
"QPushButton#btn_head:hover {\n"
"    border-image: url(:/party/images/party/hover_head.png);\n"
"}")
        self.btn_head.setText("")
        self.btn_head.setObjectName("btn_head")
        self.btn_arms = QtWidgets.QPushButton(self.page_party)
        self.btn_arms.setGeometry(QtCore.QRect(420, 50, 30, 30))
        self.btn_arms.setStyleSheet("QPushButton#btn_arms {\n"
"    border-image: url(:/party/images/party/arms.png);\n"
"}\n"
"QPushButton#btn_arms:hover {\n"
"    border-image: url(:/party/images/party/hover_arms.png);\n"
"}")
        self.btn_arms.setText("")
        self.btn_arms.setObjectName("btn_arms")
        self.btn_add = QtWidgets.QPushButton(self.page_party)
        self.btn_add.setGeometry(QtCore.QRect(420, 90, 30, 30))
        self.btn_add.setStyleSheet("QPushButton#btn_add {\n"
"    border-image: url(:/icons/images/icons/add.png);\n"
"}\n"
"QPushButton#btn_add:hover {\n"
"    border-image: url(:/icons/images/icons/hover_add.png);\n"
"}")
        self.btn_add.setText("")
        self.btn_add.setObjectName("btn_add")
        self.btn_download = QtWidgets.QPushButton(self.page_party)
        self.btn_download.setGeometry(QtCore.QRect(420, 130, 30, 30))
        self.btn_download.setStyleSheet("QPushButton#btn_download {\n"
"    border-image: url(:/icons/images/icons/download.png);\n"
"}\n"
"QPushButton#btn_download:hover {\n"
"    border-image: url(:/icons/images/icons/hover_download.png);\n"
"}")
        self.btn_download.setText("")
        self.btn_download.setObjectName("btn_download")
        self.widget_head = QtWidgets.QWidget(self.page_party)
        self.widget_head.setGeometry(QtCore.QRect(270, 0, 150, 50))
        self.widget_head.setStyleSheet("")
        self.widget_head.setObjectName("widget_head")
        self.label_bg = QtWidgets.QLabel(self.widget_head)
        self.label_bg.setGeometry(QtCore.QRect(10, 10, 130, 30))
        self.label_bg.setStyleSheet("")
        self.label_bg.setText("")
        self.label_bg.setObjectName("label_bg")
        self.slider_head = QtWidgets.QSlider(self.widget_head)
        self.slider_head.setGeometry(QtCore.QRect(20, 10, 111, 31))
        self.slider_head.setMinimum(250)
        self.slider_head.setMaximum(1250)
        self.slider_head.setProperty("value", 750)
        self.slider_head.setOrientation(QtCore.Qt.Horizontal)
        self.slider_head.setObjectName("slider_head")
        self.widget_arms = QtWidgets.QWidget(self.page_party)
        self.widget_arms.setGeometry(QtCore.QRect(270, 40, 150, 50))
        self.widget_arms.setStyleSheet("")
        self.widget_arms.setObjectName("widget_arms")
        self.label_bg_2 = QtWidgets.QLabel(self.widget_arms)
        self.label_bg_2.setGeometry(QtCore.QRect(10, 10, 130, 30))
        self.label_bg_2.setStyleSheet("")
        self.label_bg_2.setText("")
        self.label_bg_2.setObjectName("label_bg_2")
        self.slider_arms = QtWidgets.QSlider(self.widget_arms)
        self.slider_arms.setGeometry(QtCore.QRect(20, 10, 111, 31))
        self.slider_arms.setMinimum(250)
        self.slider_arms.setMaximum(1250)
        self.slider_arms.setProperty("value", 750)
        self.slider_arms.setOrientation(QtCore.Qt.Horizontal)
        self.slider_arms.setObjectName("slider_arms")
        self.label_bg_3 = QtWidgets.QLabel(self.page_party)
        self.label_bg_3.setGeometry(QtCore.QRect(20, 10, 30, 150))
        self.label_bg_3.setStyleSheet("")
        self.label_bg_3.setText("")
        self.label_bg_3.setObjectName("label_bg_3")
        self.slider_volume = QtWidgets.QSlider(self.page_party)
        self.slider_volume.setGeometry(QtCore.QRect(20, 20, 30, 130))
        self.slider_volume.setMaximum(100)
        self.slider_volume.setOrientation(QtCore.Qt.Vertical)
        self.slider_volume.setObjectName("slider_volume")
        self.label_volume = QtWidgets.QLabel(self.page_party)
        self.label_volume.setGeometry(QtCore.QRect(20, 155, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_volume.setFont(font)
        self.label_volume.setStyleSheet("color: rgb(224, 224, 226);")
        self.label_volume.setAlignment(QtCore.Qt.AlignCenter)
        self.label_volume.setObjectName("label_volume")
        self.stacked_pages.addWidget(self.page_party)
        self.page_queue = QtWidgets.QWidget()
        self.page_queue.setStyleSheet("QPushButton#btn_join, #btn_search, #btn_hide {\n"
"    background-color: rgb(20, 92, 158);\n"
"    color: rgb(224, 224, 226);\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_join:hover, #btn_search:hover, #btn_hide:hover {\n"
"    background-color: rgb(19, 55, 88);\n"
"}\n"
"QPushButton#btn_join:pressed, #btn_search:pressedr, #btn_hide:pressed {\n"
"    background-color: rgb(19, 37, 53);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgba(0,0,0,0);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(20, 92, 158);\n"
"    color: rgb(224, 224, 226);\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QListWidget#list_queue, #list_search {\n"
"    color: rgb(224,224,226);\n"
"    background-color:rgba(0,0,0,0);\n"
"    border: 2px solid rgb(20,92,158);\n"
"    border-radius: 5px;\n"
"}\n"
"QListWidget#list_queue \n"
"{\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"}\n"
"QListWidget::item:hover {\n"
"    background-color: rgb(20,92,158);\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(19,55,88);\n"
"}\n"
"\n"
"QLabel#label_queue {\n"
"    color: rgb(224, 224, 226);\n"
"    background-color: rgb(20,92,158);\n"
"    border-radius: 5px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}")
        self.page_queue.setObjectName("page_queue")
        self.frame_queue = QtWidgets.QFrame(self.page_queue)
        self.frame_queue.setGeometry(QtCore.QRect(0, 0, 471, 421))
        self.frame_queue.setStyleSheet("QWidget#widget_queue {\n"
"    background-color: rgb()\n"
"}")
        self.frame_queue.setObjectName("frame_queue")
        self.label_queue = QtWidgets.QLabel(self.frame_queue)
        self.label_queue.setGeometry(QtCore.QRect(20, 10, 160, 30))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.label_queue.setFont(font)
        self.label_queue.setStyleSheet("")
        self.label_queue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_queue.setObjectName("label_queue")
        self.list_queue = QtWidgets.QListWidget(self.frame_queue)
        self.list_queue.setGeometry(QtCore.QRect(20, 40, 160, 370))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(8)
        self.list_queue.setFont(font)
        self.list_queue.setStyleSheet("")
        self.list_queue.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_queue.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_queue.setObjectName("list_queue")
        self.list_search = QtWidgets.QListWidget(self.frame_queue)
        self.list_search.setGeometry(QtCore.QRect(190, 50, 260, 320))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(8)
        self.list_search.setFont(font)
        self.list_search.setStyleSheet("")
        self.list_search.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_search.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_search.setObjectName("list_search")
        self.input_search = QtWidgets.QLineEdit(self.frame_queue)
        self.input_search.setGeometry(QtCore.QRect(190, 10, 220, 32))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.input_search.setFont(font)
        self.input_search.setStyleSheet("")
        self.input_search.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_search.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_search.setClearButtonEnabled(True)
        self.input_search.setObjectName("input_search")
        self.btn_join = QtWidgets.QPushButton(self.frame_queue)
        self.btn_join.setGeometry(QtCore.QRect(190, 380, 220, 30))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.btn_join.setFont(font)
        self.btn_join.setStyleSheet("QPushButton#btn_shutdown {\n"
"    border-image: url(:/menu/images/menu/exit.png);\n"
"}\n"
"QPushButton#btn_shutdown:hover {\n"
"    border-image: url(:/menu/images/menu/hover_exit.png);\n"
"}")
        self.btn_join.setObjectName("btn_join")
        self.btn_hide = QtWidgets.QPushButton(self.frame_queue)
        self.btn_hide.setGeometry(QtCore.QRect(420, 380, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_hide.setFont(font)
        self.btn_hide.setStyleSheet("QPushButton#btn_hide {\n"
"    border-image: url(:/party/images/party/hide.png);\n"
"}\n"
"QPushButton#btn_hide:hover {\n"
"    border-image: url(:/party/images/party/hover_hide.png);\n"
"}")
        self.btn_hide.setText("")
        self.btn_hide.setObjectName("btn_hide")
        self.btn_search = QtWidgets.QPushButton(self.frame_queue)
        self.btn_search.setGeometry(QtCore.QRect(420, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_search.setFont(font)
        self.btn_search.setStyleSheet("QPushButton#btn_search {\n"
"    border-image: url(:/icons/images/icons/search.png);\n"
"}\n"
"QPushButton#btn_search:hover {\n"
"    border-image: url(:/icons/images/icons/hover_search.png);\n"
"}")
        self.btn_search.setText("")
        self.btn_search.setObjectName("btn_search")
        self.stacked_pages.addWidget(self.page_queue)
        self.page_chat = QtWidgets.QWidget()
        self.page_chat.setStyleSheet("QPushButton#btn_send, #btn_hide_2 {\n"
"    background-color: rgb(20, 92, 158);\n"
"    color: rgb(224, 224, 226);\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_send:hover, #btn_hide_2:hover {\n"
"    background-color: rgb(19, 55, 88);\n"
"}\n"
"QPushButton#btn_send:pressed, #btn_hide_2:pressedd {\n"
"    background-color: rgb(19, 37, 53);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgba(0,0,0,0);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(20, 92, 158);\n"
"    color: rgb(224, 224, 226);\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QPlainTextEdit {\n"
"    background-color: rgba(0,0,0,0);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(20, 92, 158);\n"
"    color: rgb(224, 224, 226);\n"
"    padding-left: 5px;\n"
"}")
        self.page_chat.setObjectName("page_chat")
        self.frame_chat = QtWidgets.QFrame(self.page_chat)
        self.frame_chat.setGeometry(QtCore.QRect(0, 0, 470, 420))
        self.frame_chat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_chat.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_chat.setObjectName("frame_chat")
        self.input_msg = QtWidgets.QLineEdit(self.frame_chat)
        self.input_msg.setGeometry(QtCore.QRect(20, 380, 351, 32))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.input_msg.setFont(font)
        self.input_msg.setStyleSheet("")
        self.input_msg.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_msg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.input_msg.setClearButtonEnabled(True)
        self.input_msg.setObjectName("input_msg")
        self.btn_hide_2 = QtWidgets.QPushButton(self.frame_chat)
        self.btn_hide_2.setGeometry(QtCore.QRect(420, 380, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_hide_2.setFont(font)
        self.btn_hide_2.setStyleSheet("QPushButton#btn_hide_2 {\n"
"    border-image: url(:/party/images/party/hide.png);\n"
"}\n"
"QPushButton#btn_hide_2:hover {\n"
"    border-image: url(:/party/images/party/hover_hide.png);\n"
"}")
        self.btn_hide_2.setText("")
        self.btn_hide_2.setObjectName("btn_hide_2")
        self.chat_history = QtWidgets.QPlainTextEdit(self.frame_chat)
        self.chat_history.setGeometry(QtCore.QRect(20, 10, 431, 361))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(8)
        self.chat_history.setFont(font)
        self.chat_history.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chat_history.setReadOnly(True)
        self.chat_history.setPlainText("")
        self.chat_history.setObjectName("chat_history")
        self.btn_send = QtWidgets.QPushButton(self.frame_chat)
        self.btn_send.setGeometry(QtCore.QRect(380, 380, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_send.setFont(font)
        self.btn_send.setStyleSheet("QPushButton#btn_send {\n"
"    border-image: url(:/icons/images/icons/send.png);\n"
"}\n"
"QPushButton#btn_send:hover {\n"
"    border-image: url(:/icons/images/icons/hover_send.png);\n"
"}")
        self.btn_send.setText("")
        self.btn_send.setObjectName("btn_send")
        self.stacked_pages.addWidget(self.page_chat)
        self.label_listeners = QtWidgets.QLabel(self.widget)
        self.label_listeners.setGeometry(QtCore.QRect(200, 15, 210, 30))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_listeners.setFont(font)
        self.label_listeners.setStyleSheet("color: rgb(224, 224, 226);")
        self.label_listeners.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_listeners.setObjectName("label_listeners")
        self.label_current = QtWidgets.QLabel(self.widget)
        self.label_current.setGeometry(QtCore.QRect(200, 35, 210, 30))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_current.setFont(font)
        self.label_current.setStyleSheet("color: rgb(224, 224, 226);")
        self.label_current.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_current.setObjectName("label_current")
        self.app_bg = QtWidgets.QLabel(self.frame_border)
        self.app_bg.setGeometry(QtCore.QRect(0, 0, 491, 601))
        self.app_bg.setStyleSheet("border-image: url(:/images/images/welcome_bg.png);")
        self.app_bg.setText("")
        self.app_bg.setObjectName("app_bg")
        self.app_bg.raise_()
        self.frame.raise_()
        PartyScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(PartyScreen)
        self.stacked_pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PartyScreen)

    def retranslateUi(self, PartyScreen):
        _translate = QtCore.QCoreApplication.translate
        PartyScreen.setWindowTitle(_translate("PartyScreen", "MainWindow"))
        self.app_name.setText(_translate("PartyScreen", "Прело"))
        self.label.setText(_translate("PartyScreen", "СНАГА КРАЈИНЕ"))
        self.label_artist.setText(_translate("PartyScreen", "Пјесмица"))
        self.label_name.setText(_translate("PartyScreen", "Артис"))
        self.label_like.setText(_translate("PartyScreen", "1"))
        self.label_dislike.setText(_translate("PartyScreen", "2"))
        self.label_time.setText(_translate("PartyScreen", "00:00"))
        self.label_length.setText(_translate("PartyScreen", "00:00"))
        self.label_volume.setText(_translate("PartyScreen", "100"))
        self.label_queue.setText(_translate("PartyScreen", "Ред чекања"))
        self.input_search.setPlaceholderText(_translate("PartyScreen", "Име пјесме"))
        self.btn_join.setText(_translate("PartyScreen", "Стани у ред чекања"))
        self.input_msg.setPlaceholderText(_translate("PartyScreen", "Унесите поруку"))
        self.label_listeners.setText(_translate("PartyScreen", "Слушаоци: 0"))
        self.label_current.setText(_translate("PartyScreen", "Тренутно пушта: никола"))
import res_rc
