# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_play.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlayScreen(object):
    def setupUi(self, PlayScreen):
        PlayScreen.setObjectName("PlayScreen")
        PlayScreen.setWindowModality(QtCore.Qt.NonModal)
        PlayScreen.resize(490, 600)
        PlayScreen.setWindowOpacity(1.0)
        PlayScreen.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(PlayScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_border = QtWidgets.QFrame(self.centralwidget)
        self.frame_border.setGeometry(QtCore.QRect(0, 0, 490, 601))
        self.frame_border.setStyleSheet("QFrame {    \n"
"    background-color: rgba(18, 18, 18, 175);\n"
"}\n"
"QLabel {\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_border.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_border.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_border.setObjectName("frame_border")
        self.frame = QtWidgets.QFrame(self.frame_border)
        self.frame.setGeometry(QtCore.QRect(10, 10, 470, 580))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 471, 580))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.frame_left = QtWidgets.QFrame(self.widget)
        self.frame_left.setGeometry(QtCore.QRect(0, 0, 130, 580))
        self.frame_left.setStyleSheet("QPushButton {\n"
"    background-color: rgb(20, 92, 158);\n"
"    color: rgb(224, 224, 226);\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(19, 55, 88);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(19, 37, 53);\n"
"}")
        self.frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.btn_song = QtWidgets.QPushButton(self.frame_left)
        self.btn_song.setGeometry(QtCore.QRect(0, 40, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_song.setFont(font)
        self.btn_song.setStyleSheet("")
        self.btn_song.setObjectName("btn_song")
        self.songs = QtWidgets.QLabel(self.frame_left)
        self.songs.setGeometry(QtCore.QRect(0, 0, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.songs.setFont(font)
        self.songs.setStyleSheet("color: rgb(224, 224, 226);")
        self.songs.setAlignment(QtCore.Qt.AlignCenter)
        self.songs.setObjectName("songs")
        self.btn_artists = QtWidgets.QPushButton(self.frame_left)
        self.btn_artists.setGeometry(QtCore.QRect(0, 80, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_artists.setFont(font)
        self.btn_artists.setStyleSheet("")
        self.btn_artists.setObjectName("btn_artists")
        self.btn_local = QtWidgets.QPushButton(self.frame_left)
        self.btn_local.setGeometry(QtCore.QRect(0, 120, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_local.setFont(font)
        self.btn_local.setStyleSheet("")
        self.btn_local.setObjectName("btn_local")
        self.btn_recent = QtWidgets.QPushButton(self.frame_left)
        self.btn_recent.setGeometry(QtCore.QRect(0, 160, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_recent.setFont(font)
        self.btn_recent.setStyleSheet("")
        self.btn_recent.setObjectName("btn_recent")
        self.playlist = QtWidgets.QLabel(self.frame_left)
        self.playlist.setGeometry(QtCore.QRect(0, 200, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.playlist.setFont(font)
        self.playlist.setStyleSheet("color: rgb(224, 224, 226);")
        self.playlist.setAlignment(QtCore.Qt.AlignCenter)
        self.playlist.setObjectName("playlist")
        self.btn_new = QtWidgets.QPushButton(self.frame_left)
        self.btn_new.setGeometry(QtCore.QRect(0, 530, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_new.setFont(font)
        self.btn_new.setStyleSheet("")
        self.btn_new.setObjectName("btn_new")
        self.list_playlist = QtWidgets.QListWidget(self.frame_left)
        self.list_playlist.setGeometry(QtCore.QRect(0, 240, 130, 290))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.list_playlist.setFont(font)
        self.list_playlist.setStyleSheet("QListWidget#list_playlist {\n"
"    color: rgb(224,224,226);\n"
"    background-color:rgba(0,0,0,0);\n"
"    border-radius: 0px;\n"
"}\n"
"QListWidget::item:hover {\n"
"    background-color: rgb(20,92,158);\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(19,55,88);\n"
"}")
        self.list_playlist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_playlist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_playlist.setObjectName("list_playlist")
        item = QtWidgets.QListWidgetItem()
        self.list_playlist.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_playlist.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_playlist.addItem(item)
        self.stacked_pages = QtWidgets.QStackedWidget(self.widget)
        self.stacked_pages.setGeometry(QtCore.QRect(130, 0, 340, 580))
        self.stacked_pages.setStyleSheet("QStackedWidget {\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.stacked_pages.setObjectName("stacked_pages")
        self.page_songs = QtWidgets.QWidget()
        self.page_songs.setObjectName("page_songs")
        self.widget_current = QtWidgets.QWidget(self.page_songs)
        self.widget_current.setGeometry(QtCore.QRect(0, 0, 340, 161))
        self.widget_current.setStyleSheet("")
        self.widget_current.setObjectName("widget_current")
        self.label_art = QtWidgets.QLabel(self.widget_current)
        self.label_art.setGeometry(QtCore.QRect(10, 10, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.label_art.setFont(font)
        self.label_art.setStyleSheet("QLabel#label_art {\n"
"    border: 2px solid;\n"
"    background-color: rgb(224,224,226);\n"
"}")
        self.label_art.setAlignment(QtCore.Qt.AlignCenter)
        self.label_art.setObjectName("label_art")
        self.label_name = QtWidgets.QLabel(self.widget_current)
        self.label_name.setGeometry(QtCore.QRect(80, 10, 251, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("color: rgb(224, 224, 226);")
        self.label_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_name.setObjectName("label_name")
        self.label_artist = QtWidgets.QLabel(self.widget_current)
        self.label_artist.setGeometry(QtCore.QRect(80, 30, 251, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_artist.setFont(font)
        self.label_artist.setStyleSheet("color: rgb(224, 224, 226);")
        self.label_artist.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_artist.setObjectName("label_artist")
        self.horizontalSlider = QtWidgets.QSlider(self.widget_current)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 140, 320, 15))
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    background-color: rgb(224,224,226);\n"
"    height: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    width: 12px;\n"
"    background-color: rgb(20,92,158);\n"
"    border-radius: 5px;\n"
"    margin: -5px 0;\n"
"}")
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setPageStep(0)
        self.horizontalSlider.setProperty("value", 13)
        self.horizontalSlider.setSliderPosition(13)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickInterval(0)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.btn_shuffle = QtWidgets.QPushButton(self.widget_current)
        self.btn_shuffle.setGeometry(QtCore.QRect(50, 90, 40, 40))
        self.btn_shuffle.setStyleSheet("QPushButton#btn_shuffle {\n"
"    border-image: url(:/play/images/play/shuffle.png);\n"
"}\n"
"QPushButton#btn_shuffle:hover {\n"
"    border-image: url(:/play/images/play/hover_shuffle.png);\n"
"}")
        self.btn_shuffle.setText("")
        self.btn_shuffle.setObjectName("btn_shuffle")
        self.btn_previous = QtWidgets.QPushButton(self.widget_current)
        self.btn_previous.setGeometry(QtCore.QRect(100, 90, 40, 40))
        self.btn_previous.setStyleSheet("QPushButton#btn_previous {\n"
"    border-image: url(:/play/images/play/previous.png);\n"
"}\n"
"QPushButton#btn_previous:hover {\n"
"    border-image: url(:/play/images/play/hover_previous.png);\n"
"}")
        self.btn_previous.setText("")
        self.btn_previous.setObjectName("btn_previous")
        self.btn_play = QtWidgets.QPushButton(self.widget_current)
        self.btn_play.setGeometry(QtCore.QRect(150, 90, 40, 40))
        self.btn_play.setStyleSheet("QPushButton#btn_play {\n"
"    border-image: url(:/play/images/play/play.png);\n"
"}\n"
"QPushButton#btn_play:hover {\n"
"    border-image: url(:/play/images/play/hover_play.png);\n"
"}")
        self.btn_play.setText("")
        self.btn_play.setObjectName("btn_play")
        self.btn_next = QtWidgets.QPushButton(self.widget_current)
        self.btn_next.setGeometry(QtCore.QRect(200, 90, 40, 40))
        self.btn_next.setStyleSheet("QPushButton#btn_next {\n"
"    border-image: url(:/play/images/play/next.png);\n"
"}\n"
"QPushButton#btn_next:hover {\n"
"    border-image: url(:/play/images/play/hover_next.png);\n"
"}")
        self.btn_next.setText("")
        self.btn_next.setObjectName("btn_next")
        self.btn_repeat_all = QtWidgets.QPushButton(self.widget_current)
        self.btn_repeat_all.setGeometry(QtCore.QRect(250, 90, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_repeat_all.setFont(font)
        self.btn_repeat_all.setStyleSheet("QPushButton#btn_repeat_all {\n"
"    border-image: url(:/play/images/play/repeat.png);\n"
"    color: rgb(224,224,226);\n"
"}\n"
"QPushButton#btn_repeat_all:hover {\n"
"    border-image: url(:/play/images/play/hover_repeat.png);\n"
"}")
        self.btn_repeat_all.setObjectName("btn_repeat_all")
        self.btn_back = QtWidgets.QPushButton(self.widget_current)
        self.btn_back.setGeometry(QtCore.QRect(300, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("QPushButton#btn_back {\n"
"    border-image: url(:/menu/images/menu/exit.png);\n"
"}\n"
"QPushButton#btn_back:hover {\n"
"    border-image: url(:/menu/images/menu/hover_exit.png);\n"
"}")
        self.btn_back.setText("")
        self.btn_back.setObjectName("btn_back")
        self.btn_shuffle_off = QtWidgets.QPushButton(self.widget_current)
        self.btn_shuffle_off.setGeometry(QtCore.QRect(50, 90, 40, 40))
        self.btn_shuffle_off.setStyleSheet("QPushButton#btn_shuffle_off {\n"
"    border-image: url(:/play/images/play/shuffle_off.png);\n"
"}\n"
"QPushButton#btn_shuffle_off:hover {\n"
"    border-image: url(:/play/images/play/hover_shuffle_off.png);\n"
"}")
        self.btn_shuffle_off.setText("")
        self.btn_shuffle_off.setObjectName("btn_shuffle_off")
        self.btn_repeat_one = QtWidgets.QPushButton(self.widget_current)
        self.btn_repeat_one.setGeometry(QtCore.QRect(250, 90, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_repeat_one.setFont(font)
        self.btn_repeat_one.setStyleSheet("QPushButton#btn_repeat_one {\n"
"    border-image: url(:/play/images/play/repeat.png);\n"
"    color: rgb(224,224,226);\n"
"}\n"
"QPushButton#btn_repeat_one:hover {\n"
"    border-image: url(:/play/images/play/hover_repeat.png);\n"
"}")
        self.btn_repeat_one.setObjectName("btn_repeat_one")
        self.btn_pause = QtWidgets.QPushButton(self.widget_current)
        self.btn_pause.setGeometry(QtCore.QRect(150, 90, 40, 40))
        self.btn_pause.setStyleSheet("QPushButton#btn_pause {\n"
"    border-image: url(:/play/images/play/pause.png);\n"
"}\n"
"QPushButton#btn_pause:hover {\n"
"    border-image: url(:/play/images/play/hover_pause.png);\n"
"}")
        self.btn_pause.setText("")
        self.btn_pause.setObjectName("btn_pause")
        self.widget_playlist = QtWidgets.QWidget(self.page_songs)
        self.widget_playlist.setGeometry(QtCore.QRect(0, 159, 340, 411))
        self.widget_playlist.setStyleSheet("")
        self.widget_playlist.setObjectName("widget_playlist")
        self.list_songs = QtWidgets.QListWidget(self.widget_playlist)
        self.list_songs.setGeometry(QtCore.QRect(10, 0, 320, 410))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.list_songs.setFont(font)
        self.list_songs.setStyleSheet("QListWidget#list_songs {\n"
"    color: rgb(224,224,226);\n"
"    background-color:rgba(0,0,0,0);\n"
"    border: 2px solid rgb(20,92,158);\n"
"    border-radius: 5px;\n"
"}\n"
"QListWidget::item:hover {\n"
"    background-color: rgb(20,92,158);\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(19,55,88);\n"
"}")
        self.list_songs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_songs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_songs.setObjectName("list_songs")
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_songs.addItem(item)
        self.stacked_pages.addWidget(self.page_songs)
        self.page_new = QtWidgets.QWidget()
        self.page_new.setObjectName("page_new")
        self.stacked_pages.addWidget(self.page_new)
        self.app_bg = QtWidgets.QLabel(self.frame_border)
        self.app_bg.setGeometry(QtCore.QRect(0, 0, 491, 601))
        self.app_bg.setStyleSheet("border-image: url(:/images/images/welcome_bg.png);")
        self.app_bg.setText("")
        self.app_bg.setObjectName("app_bg")
        self.app_bg.raise_()
        self.frame.raise_()
        PlayScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(PlayScreen)
        self.stacked_pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PlayScreen)

    def retranslateUi(self, PlayScreen):
        _translate = QtCore.QCoreApplication.translate
        PlayScreen.setWindowTitle(_translate("PlayScreen", "MainWindow"))
        self.btn_song.setText(_translate("PlayScreen", "Пјесме"))
        self.songs.setText(_translate("PlayScreen", "Ваша музика"))
        self.btn_artists.setText(_translate("PlayScreen", "Умјетници"))
        self.btn_local.setText(_translate("PlayScreen", "Скинуте пјесме"))
        self.btn_recent.setText(_translate("PlayScreen", "Недавно слушано"))
        self.playlist.setText(_translate("PlayScreen", "Албуми"))
        self.btn_new.setText(_translate("PlayScreen", "Нови албум"))
        __sortingEnabled = self.list_playlist.isSortingEnabled()
        self.list_playlist.setSortingEnabled(False)
        item = self.list_playlist.item(0)
        item.setText(_translate("PlayScreen", "1"))
        item = self.list_playlist.item(1)
        item.setText(_translate("PlayScreen", "22"))
        item = self.list_playlist.item(2)
        item.setText(_translate("PlayScreen", "333"))
        self.list_playlist.setSortingEnabled(__sortingEnabled)
        self.label_art.setText(_translate("PlayScreen", "ART"))
        self.label_name.setText(_translate("PlayScreen", "Артис"))
        self.label_artist.setText(_translate("PlayScreen", "Пјесмица"))
        self.btn_repeat_all.setText(_translate("PlayScreen", "A"))
        self.btn_repeat_one.setText(_translate("PlayScreen", "1"))
        __sortingEnabled = self.list_songs.isSortingEnabled()
        self.list_songs.setSortingEnabled(False)
        item = self.list_songs.item(0)
        item.setText(_translate("PlayScreen", "1"))
        item = self.list_songs.item(1)
        item.setText(_translate("PlayScreen", "22"))
        item = self.list_songs.item(2)
        item.setText(_translate("PlayScreen", "333"))
        self.list_songs.setSortingEnabled(__sortingEnabled)
import res_rc
