# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuScreen(object):
    def setupUi(self, MenuScreen):
        MenuScreen.setObjectName("MenuScreen")
        MenuScreen.setWindowModality(QtCore.Qt.NonModal)
        MenuScreen.resize(490, 600)
        MenuScreen.setWindowOpacity(1.0)
        MenuScreen.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MenuScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_border = QtWidgets.QFrame(self.centralwidget)
        self.frame_border.setGeometry(QtCore.QRect(0, 0, 490, 601))
        self.frame_border.setStyleSheet("QFrame {    \n"
"    background-color: rgba(18, 18, 18, 175);\n"
"}\n"
"QLabel {\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_border.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_border.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_border.setObjectName("frame_border")
        self.frame = QtWidgets.QFrame(self.frame_border)
        self.frame.setGeometry(QtCore.QRect(10, 10, 470, 580))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 471, 580))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.app_name = QtWidgets.QLabel(self.widget)
        self.app_name.setGeometry(QtCore.QRect(20, 10, 191, 60))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(42)
        font.setBold(True)
        font.setWeight(75)
        self.app_name.setFont(font)
        self.app_name.setStyleSheet("color: rgb(20, 92, 158);")
        self.app_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.app_name.setAlignment(QtCore.Qt.AlignCenter)
        self.app_name.setObjectName("app_name")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(86, 45, 111, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(224,224,226);")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.btn_play = QtWidgets.QPushButton(self.widget)
        self.btn_play.setGeometry(QtCore.QRect(30, 90, 60, 60))
        self.btn_play.setStyleSheet("QPushButton#btn_play {\n"
"    border-image: url(:/menu/images/menu/play.png);\n"
"}\n"
"QPushButton#btn_play:hover {\n"
"    border-image: url(:/menu/images/menu/hover_play.png);\n"
"}")
        self.btn_play.setText("")
        self.btn_play.setObjectName("btn_play")
        self.btn_search = QtWidgets.QPushButton(self.widget)
        self.btn_search.setGeometry(QtCore.QRect(30, 170, 60, 60))
        self.btn_search.setStyleSheet("QPushButton#btn_search {\n"
"    border-image: url(:/menu/images/menu/search.png);\n"
"}\n"
"QPushButton#btn_search:hover {\n"
"    border-image: url(:/menu/images/menu/hover_search.png);\n"
"}")
        self.btn_search.setText("")
        self.btn_search.setObjectName("btn_search")
        self.btn_friends = QtWidgets.QPushButton(self.widget)
        self.btn_friends.setGeometry(QtCore.QRect(30, 250, 60, 60))
        self.btn_friends.setStyleSheet("QPushButton#btn_friends {\n"
"    border-image: url(:/menu/images/menu/friends.png);\n"
"}\n"
"QPushButton#btn_friends:hover {\n"
"    border-image: url(:/menu/images/menu/hover_friends.png);\n"
"}")
        self.btn_friends.setText("")
        self.btn_friends.setObjectName("btn_friends")
        self.btn_chat = QtWidgets.QPushButton(self.widget)
        self.btn_chat.setGeometry(QtCore.QRect(30, 330, 60, 60))
        self.btn_chat.setStyleSheet("QPushButton#btn_chat {\n"
"    border-image: url(:/menu/images/menu/chat.png);\n"
"}\n"
"QPushButton#btn_chat:hover {\n"
"    border-image: url(:/menu/images/menu/hover_chat.png);\n"
"}")
        self.btn_chat.setText("")
        self.btn_chat.setObjectName("btn_chat")
        self.btn_settings = QtWidgets.QPushButton(self.widget)
        self.btn_settings.setGeometry(QtCore.QRect(30, 410, 60, 60))
        self.btn_settings.setStyleSheet("QPushButton#btn_settings {\n"
"    border-image: url(:/menu/images/menu/settings.png);\n"
"}\n"
"QPushButton#btn_settings:hover {\n"
"    border-image: url(:/menu/images/menu/hover_settings.png);\n"
"}")
        self.btn_settings.setText("")
        self.btn_settings.setObjectName("btn_settings")
        self.btn_about = QtWidgets.QPushButton(self.widget)
        self.btn_about.setGeometry(QtCore.QRect(30, 490, 60, 60))
        self.btn_about.setStyleSheet("QPushButton#btn_about {\n"
"    border-image: url(:/menu/images/menu/about.png);\n"
"}\n"
"QPushButton#btn_about:hover {\n"
"    border-image: url(:/menu/images/menu/hover_about.png);\n"
"}")
        self.btn_about.setText("")
        self.btn_about.setObjectName("btn_about")
        self.btn_admin = QtWidgets.QPushButton(self.widget)
        self.btn_admin.setGeometry(QtCore.QRect(400, 30, 40, 40))
        self.btn_admin.setStyleSheet("QPushButton#btn_admin {\n"
"    border-image: url(:/menu/images/menu/admin.png);\n"
"}\n"
"QPushButton#btn_admin:hover {\n"
"    border-image: url(:/menu/images/menu/hover_admin.png);\n"
"}")
        self.btn_admin.setText("")
        self.btn_admin.setObjectName("btn_admin")
        self.btn_shutdown = QtWidgets.QPushButton(self.widget)
        self.btn_shutdown.setGeometry(QtCore.QRect(400, 510, 40, 40))
        self.btn_shutdown.setStyleSheet("QPushButton#btn_shutdown {\n"
"    border-image: url(:/menu/images/menu/exit.png);\n"
"}\n"
"QPushButton#btn_shutdown:hover {\n"
"    border-image: url(:/menu/images/menu/hover_exit.png);\n"
"}")
        self.btn_shutdown.setText("")
        self.btn_shutdown.setObjectName("btn_shutdown")
        self.btn_party = QtWidgets.QPushButton(self.widget)
        self.btn_party.setGeometry(QtCore.QRect(340, 200, 200, 200))
        self.btn_party.setStyleSheet("QPushButton#btn_party {\n"
"    border-image: url(:/menu/images/menu/party.png);\n"
"}\n"
"QPushButton#btn_party:hover {\n"
"    border-image: url(:/menu/images/menu/hover_party.png);\n"
"}")
        self.btn_party.setText("")
        self.btn_party.setObjectName("btn_party")
        self.app_bg = QtWidgets.QLabel(self.frame_border)
        self.app_bg.setGeometry(QtCore.QRect(0, 0, 491, 601))
        self.app_bg.setStyleSheet("border-image: url(:/images/images/welcome_bg.png);")
        self.app_bg.setText("")
        self.app_bg.setObjectName("app_bg")
        self.app_bg.raise_()
        self.frame.raise_()
        MenuScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(MenuScreen)
        QtCore.QMetaObject.connectSlotsByName(MenuScreen)

    def retranslateUi(self, MenuScreen):
        _translate = QtCore.QCoreApplication.translate
        MenuScreen.setWindowTitle(_translate("MenuScreen", "MainWindow"))
        self.app_name.setText(_translate("MenuScreen", "Прело"))
        self.label.setText(_translate("MenuScreen", "СНАГА КРАЈИНЕ"))
import res_rc
