# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tutorial.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TutorialScreen(object):
    def setupUi(self, TutorialScreen):
        TutorialScreen.setObjectName("TutorialScreen")
        TutorialScreen.setWindowModality(QtCore.Qt.NonModal)
        TutorialScreen.resize(490, 600)
        TutorialScreen.setWindowOpacity(1.0)
        TutorialScreen.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(TutorialScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_border = QtWidgets.QFrame(self.centralwidget)
        self.frame_border.setGeometry(QtCore.QRect(0, 0, 490, 601))
        self.frame_border.setStyleSheet("QFrame {    \n"
"    background-color: rgba(18, 18, 18, 175);\n"
"}\n"
"QLabel {\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_border.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_border.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_border.setObjectName("frame_border")
        self.frame = QtWidgets.QFrame(self.frame_border)
        self.frame.setGeometry(QtCore.QRect(10, 10, 470, 580))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 471, 580))
        self.widget.setStyleSheet("QPlainTextEdit {\n"
"    background-color: rgba(0,0,0,0);\n"
"    border: none;\n"
"    color: rgb(224,224,226);\n"
"}")
        self.widget.setObjectName("widget")
        self.app_name = QtWidgets.QLabel(self.widget)
        self.app_name.setGeometry(QtCore.QRect(20, 10, 191, 60))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(42)
        font.setBold(True)
        font.setWeight(75)
        self.app_name.setFont(font)
        self.app_name.setStyleSheet("color: rgb(20, 92, 158);")
        self.app_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.app_name.setAlignment(QtCore.Qt.AlignCenter)
        self.app_name.setObjectName("app_name")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(86, 45, 111, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(224,224,226);")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.btn_play = QtWidgets.QPushButton(self.widget)
        self.btn_play.setGeometry(QtCore.QRect(30, 90, 60, 60))
        self.btn_play.setStyleSheet("QPushButton#btn_play {\n"
"    border-image: url(:/menu/images/menu/play.png);\n"
"}\n"
"QPushButton#btn_play:hover {\n"
"    border-image: url(:/menu/images/menu/hover_play.png);\n"
"}")
        self.btn_play.setText("")
        self.btn_play.setObjectName("btn_play")
        self.btn_search = QtWidgets.QPushButton(self.widget)
        self.btn_search.setGeometry(QtCore.QRect(30, 170, 60, 60))
        self.btn_search.setStyleSheet("QPushButton#btn_search {\n"
"    border-image: url(:/menu/images/menu/search.png);\n"
"}\n"
"QPushButton#btn_search:hover {\n"
"    border-image: url(:/menu/images/menu/hover_search.png);\n"
"}")
        self.btn_search.setText("")
        self.btn_search.setObjectName("btn_search")
        self.btn_friends = QtWidgets.QPushButton(self.widget)
        self.btn_friends.setGeometry(QtCore.QRect(30, 250, 60, 60))
        self.btn_friends.setStyleSheet("QPushButton#btn_friends {\n"
"    border-image: url(:/menu/images/menu/friends.png);\n"
"}\n"
"QPushButton#btn_friends:hover {\n"
"    border-image: url(:/menu/images/menu/hover_friends.png);\n"
"}")
        self.btn_friends.setText("")
        self.btn_friends.setObjectName("btn_friends")
        self.btn_chat = QtWidgets.QPushButton(self.widget)
        self.btn_chat.setGeometry(QtCore.QRect(30, 330, 60, 60))
        self.btn_chat.setStyleSheet("QPushButton#btn_chat {\n"
"    border-image: url(:/menu/images/menu/chat.png);\n"
"}\n"
"QPushButton#btn_chat:hover {\n"
"    border-image: url(:/menu/images/menu/hover_chat.png);\n"
"}")
        self.btn_chat.setText("")
        self.btn_chat.setObjectName("btn_chat")
        self.btn_settings = QtWidgets.QPushButton(self.widget)
        self.btn_settings.setGeometry(QtCore.QRect(30, 410, 60, 60))
        self.btn_settings.setStyleSheet("QPushButton#btn_settings {\n"
"    border-image: url(:/menu/images/menu/settings.png);\n"
"}\n"
"QPushButton#btn_settings:hover {\n"
"    border-image: url(:/menu/images/menu/hover_settings.png);\n"
"}")
        self.btn_settings.setText("")
        self.btn_settings.setObjectName("btn_settings")
        self.btn_about = QtWidgets.QPushButton(self.widget)
        self.btn_about.setGeometry(QtCore.QRect(30, 490, 60, 60))
        self.btn_about.setStyleSheet("QPushButton#btn_about {\n"
"    border-image: url(:/menu/images/menu/about.png);\n"
"}\n"
"QPushButton#btn_about:hover {\n"
"    border-image: url(:/menu/images/menu/hover_about.png);\n"
"}")
        self.btn_about.setText("")
        self.btn_about.setObjectName("btn_about")
        self.widget_tutorial = QtWidgets.QWidget(self.widget)
        self.widget_tutorial.setGeometry(QtCore.QRect(0, 0, 471, 581))
        self.widget_tutorial.setObjectName("widget_tutorial")
        self.btn_next = QtWidgets.QPushButton(self.widget_tutorial)
        self.btn_next.setGeometry(QtCore.QRect(280, 280, 171, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_next.setFont(font)
        self.btn_next.setStyleSheet("QPushButton#btn_next {\n"
"    background-color: rgb(20, 92, 158);\n"
"    color: rgb(224, 224, 226);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btn_next:hover {\n"
"    background-color: rgb(19, 55, 88);\n"
"}\n"
"QPushButton#btn_next:pressed {\n"
"    background-color: rgb(19, 37, 53);\n"
"}")
        self.btn_next.setObjectName("btn_next")
        self.step_1 = QtWidgets.QLabel(self.widget_tutorial)
        self.step_1.setGeometry(QtCore.QRect(70, -30, 256, 256))
        self.step_1.setStyleSheet("border-image: url(:/tutorial/images/tutorial/step_1.png);")
        self.step_1.setText("")
        self.step_1.setObjectName("step_1")
        self.step_2 = QtWidgets.QLabel(self.widget_tutorial)
        self.step_2.setGeometry(QtCore.QRect(30, 120, 256, 256))
        self.step_2.setStyleSheet("border-image: url(:/tutorial/images/tutorial/step_2.png);")
        self.step_2.setText("")
        self.step_2.setObjectName("step_2")
        self.step_3 = QtWidgets.QLabel(self.widget_tutorial)
        self.step_3.setGeometry(QtCore.QRect(20, 230, 256, 256))
        self.step_3.setStyleSheet("border-image: url(:/tutorial/images/tutorial/step_3.png);")
        self.step_3.setText("")
        self.step_3.setObjectName("step_3")
        self.step_4 = QtWidgets.QLabel(self.widget_tutorial)
        self.step_4.setGeometry(QtCore.QRect(40, 240, 256, 256))
        self.step_4.setStyleSheet("border-image: url(:/tutorial/images/tutorial/step_4.png);")
        self.step_4.setText("")
        self.step_4.setObjectName("step_4")
        self.step_5 = QtWidgets.QLabel(self.widget_tutorial)
        self.step_5.setGeometry(QtCore.QRect(50, 320, 256, 256))
        self.step_5.setStyleSheet("border-image: url(:/tutorial/images/tutorial/step_5.png);")
        self.step_5.setText("")
        self.step_5.setObjectName("step_5")
        self.step_6 = QtWidgets.QLabel(self.widget_tutorial)
        self.step_6.setGeometry(QtCore.QRect(80, 410, 256, 256))
        self.step_6.setStyleSheet("border-image: url(:/tutorial/images/tutorial/step_6.png);")
        self.step_6.setText("")
        self.step_6.setObjectName("step_6")
        self.text_1 = QtWidgets.QPlainTextEdit(self.widget_tutorial)
        self.text_1.setGeometry(QtCore.QRect(230, 0, 240, 100))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.text_1.setFont(font)
        self.text_1.setStyleSheet("")
        self.text_1.setObjectName("text_1")
        self.text_2 = QtWidgets.QPlainTextEdit(self.widget_tutorial)
        self.text_2.setGeometry(QtCore.QRect(180, 140, 240, 100))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.text_2.setFont(font)
        self.text_2.setStyleSheet("")
        self.text_2.setObjectName("text_2")
        self.text_3 = QtWidgets.QPlainTextEdit(self.widget_tutorial)
        self.text_3.setGeometry(QtCore.QRect(0, 400, 161, 181))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.text_3.setFont(font)
        self.text_3.setStyleSheet("")
        self.text_3.setObjectName("text_3")
        self.text_4 = QtWidgets.QPlainTextEdit(self.widget_tutorial)
        self.text_4.setGeometry(QtCore.QRect(170, 430, 240, 141))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.text_4.setFont(font)
        self.text_4.setStyleSheet("")
        self.text_4.setObjectName("text_4")
        self.text_5 = QtWidgets.QPlainTextEdit(self.widget_tutorial)
        self.text_5.setGeometry(QtCore.QRect(220, 310, 240, 131))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.text_5.setFont(font)
        self.text_5.setStyleSheet("")
        self.text_5.setObjectName("text_5")
        self.text_6 = QtWidgets.QPlainTextEdit(self.widget_tutorial)
        self.text_6.setGeometry(QtCore.QRect(120, 390, 240, 171))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.text_6.setFont(font)
        self.text_6.setStyleSheet("")
        self.text_6.setObjectName("text_6")
        self.app_bg = QtWidgets.QLabel(self.frame_border)
        self.app_bg.setGeometry(QtCore.QRect(0, 0, 491, 601))
        self.app_bg.setStyleSheet("border-image: url(:/images/images/welcome_bg.png);")
        self.app_bg.setText("")
        self.app_bg.setObjectName("app_bg")
        self.app_bg.raise_()
        self.frame.raise_()
        TutorialScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(TutorialScreen)
        QtCore.QMetaObject.connectSlotsByName(TutorialScreen)

    def retranslateUi(self, TutorialScreen):
        _translate = QtCore.QCoreApplication.translate
        TutorialScreen.setWindowTitle(_translate("TutorialScreen", "MainWindow"))
        self.app_name.setText(_translate("TutorialScreen", "Прело"))
        self.label.setText(_translate("TutorialScreen", "СНАГА КРАЈИНЕ"))
        self.btn_next.setText(_translate("TutorialScreen", "Следећи корак ( 1 / 6)"))
        self.text_1.setPlainText(_translate("TutorialScreen", "Корак 1:\n"
"Ово дугме користите да би слушали музику."))
        self.text_2.setPlainText(_translate("TutorialScreen", "Корак 2:\n"
"У овај мени улазите да би нашли музику коју желите да слушаште."))
        self.text_3.setPlainText(_translate("TutorialScreen", "Корак 3:\n"
"Пријатељи, ту можете пронаћи ваше пријатеље и погледати шта слушају."))
        self.text_4.setPlainText(_translate("TutorialScreen", "Корак 4:\n"
"Овде улазите у мени за дописивање. Ту се можете дописивати са својим пријатељима, али и упознати нове људе."))
        self.text_5.setPlainText(_translate("TutorialScreen", "Корак 5:\n"
"Ово су подешавања, ту можете промјенити вашу лозинку, избрисати ваше пјесме и слично."))
        self.text_6.setPlainText(_translate("TutorialScreen", "Корак 6:\n"
"Овде можете информације о нама. Запратите нас. То би био крај туторијала. Надамо се да ћете уживати у нашој апликацији.\n"
""))
import res_rc
