# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PopupScreen(object):
    def setupUi(self, PopupScreen):
        PopupScreen.setObjectName("PopupScreen")
        PopupScreen.setWindowModality(QtCore.Qt.NonModal)
        PopupScreen.resize(490, 220)
        PopupScreen.setWindowOpacity(1.0)
        PopupScreen.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(PopupScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_border = QtWidgets.QFrame(self.centralwidget)
        self.frame_border.setGeometry(QtCore.QRect(0, 0, 490, 220))
        self.frame_border.setStyleSheet("QFrame {    \n"
"    background-color: rgba(18, 18, 18, 175);\n"
"}\n"
"QLabel {\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_border.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_border.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_border.setObjectName("frame_border")
        self.frame = QtWidgets.QFrame(self.frame_border)
        self.frame.setGeometry(QtCore.QRect(10, 10, 470, 200))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.subtitle = QtWidgets.QLabel(self.frame)
        self.subtitle.setGeometry(QtCore.QRect(0, 45, 470, 40))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.subtitle.setFont(font)
        self.subtitle.setStyleSheet("color: rgb(224,224,226);")
        self.subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitle.setObjectName("subtitle")
        self.title = QtWidgets.QLabel(self.frame)
        self.title.setGeometry(QtCore.QRect(0, 0, 470, 60))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(42)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(20, 92, 158);")
        self.title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.info = QtWidgets.QPlainTextEdit(self.frame)
        self.info.setGeometry(QtCore.QRect(10, 85, 450, 80))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.info.setFont(font)
        self.info.setStyleSheet("QPlainTextEdit {\n"
"    background-color: rgba(20,92,158,150);\n"
"    color: rgb(224,224,226);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(20,92,158);\n"
"}")
        self.info.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.info.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.info.setReadOnly(True)
        self.info.setObjectName("info")
        self.btn_back = QtWidgets.QPushButton(self.frame)
        self.btn_back.setGeometry(QtCore.QRect(10, 160, 450, 30))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("QPushButton#btn_back {\n"
"    background-color: rgb(20,92,158);\n"
"    color: rgb(224,224,226);\n"
"    border-radius: 5px;\n"
"}")
        self.btn_back.setObjectName("btn_back")
        PopupScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(PopupScreen)
        QtCore.QMetaObject.connectSlotsByName(PopupScreen)

    def retranslateUi(self, PopupScreen):
        _translate = QtCore.QCoreApplication.translate
        PopupScreen.setWindowTitle(_translate("PopupScreen", "MainWindow"))
        self.subtitle.setText(_translate("PopupScreen", "СНАГА КРАЈИНЕ"))
        self.title.setText(_translate("PopupScreen", "Прело"))
        self.info.setPlainText(_translate("PopupScreen", "Инфо #1\n"
"Инфо #2\n"
"Инфо #3"))
        self.btn_back.setText(_translate("PopupScreen", "НАЗАД"))
import res_rc
